# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Ben's Updates
paginate:       5
baseurl:        ""
url:            "https://benash.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Benjamin Nash
  url:          https://benash.github.io
  email:        benash@umich.edu

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/benash

# Plugins
plugins:
  - jekyll-paginate
